DASHBOARD_DATA = {
    "topCards": [
        {
            "icon": "Activity",
            "value": "142",
            "label": "Funds Monitored",
            "percentage": "8.2%",
            "percentageColor": "#22c55e",
            "trendIcon": "ArrowUpRight",
        },
        {
            "icon": "DollarSign",
            "value": "$15.0B",
            "label": "Total AUM Tracked",
            "percentage": "12.5%",
            "percentageColor": "#22c55e",
            "trendIcon": "ArrowUpRight",
        },
        {
            "icon": "TrendingUp",
            "value": "+12.5%",
            "label": "Average YTD Return",
            "percentage": "8.2%",
            "percentageColor": "#22c55e",
            "trendIcon": "ArrowUpRight",
        },
        {
            "icon": "AlertTriangle",
            "value": "24",
            "label": "Active Alerts",
            "percentage": "-15%",
            "percentageColor": "#c52222",
            "trendIcon": "ArrowDownRight",
        },
    ],

    "allocationData": [
        {
            "label": "Hedge Funds",
            "value": 32,
            "color": "#4625eb",
        },
        {
            "label": "Private Equity",
            "value": 25,
            "color": "#628ce7",
        },
        {
            "label": "Venture Capital",
            "value": 18,
            "color": "#14ac25",
        },
        {
            "label": "Real Assets",
            "value": 12,
            "color": "#eb7b25",
        },
        {
            "label": "Fixed Income",
            "value": 8,
            "color": "#eb2525",
        },
        {
            "label": "Public Equity",
            "value": 5,
            "color": "#c04cd7",
        },
    ],

    "months": [
        "Jul",
        "Aug",
        "Sep",
        "Oct",
        "Nov",
        "Dec",
        "Jan",
        "Feb",
        "Mar",
        "Apr",
        "May",
        "Jun",
    ],

    "portfolioValues": [
        2,
        3.9,
        1.5,
        5,
        4,
        6,
        8,
        7,
        9,
        11,
        10,
        12.3,
    ],

    "benchmarkValues": [
        2,
        2.5,
        3,
        3.6,
        4.2,
        4.9,
        5.5,
        6.1,
        6.7,
        7.2,
        7.6,
        8,
    ],

    "alerts": [
        {
            "icon": "TrendingUp",
            "iconColor": "#616161",
            "title": "Tiger Global +25% YTD",
            "description": "Outperforming benchmark by 17.3pp",
            "time": "2h ago",
        },
        {
            "icon": "AlertTriangle",
            "iconColor": "#f59e0b",
            "title": "Bridgewater drawdown alert",
            "description": "Pure alpha fund down -3.1% YTD",
            "time": "5h ago",
        },
        {
            "icon": "Users",
            "iconColor": "#3b82f6",
            "title": "PM departure at Citizel",
            "description": "Senior PM Alex Chen leaving",
            "time": "6h ago",
        },
        {
            "icon": "Activity",
            "iconColor": "#616161",
            "title": "Baupost ADV amendment",
            "description": "Updated Form ADV filed with SEC",
            "time": "1d ago",
        },
        {
            "icon": "TrendingUp",
            "iconColor": "#616161",
            "title": "Renaissance +32.1%",
            "description": "Top performer in universe",
            "time": "1d ago",
        },
    ],
}